# Generated by Django 5.2.6 on 2025-09-21 10:18

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaberlesmeKesinti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modem', models.CharField(db_index=True, max_length=64)),
                ('baslangic', core.fields.DateTimeSecField()),
                ('bitis', core.fields.DateTimeSecField()),
                ('sure', models.IntegerField()),
                ('created_at', core.fields.DateTimeSecField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Haberleşme Kesinti',
                'verbose_name_plural': 'Haberleşme Kesintileri',
                'constraints': [models.UniqueConstraint(fields=('modem', 'baslangic', 'bitis'), name='uniq_modem_baslangic_bitis')],
            },
        ),
    ]
